.TH "src/utils Directory Reference" 3 "Sun Apr 9 2023" "OpenGL Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/utils Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcolour\&.h\fP"
.br
.ti -1c
.RI "file \fBglm_utils\&.h\fP"
.br
.ti -1c
.RI "file \fBmaterial\&.h\fP"
.br
.ti -1c
.RI "file \fBvertex\&.h\fP"
.br
.in -1c
