.TH "Logger" 3 "Sun Apr 9 2023" "OpenGL Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Logger
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <logger\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInit\fP ()"
.br
.ti -1c
.RI "void \fBShutdown\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB11\fP of file \fBlogger\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Logger::Init ()"

.PP
Definition at line \fB3\fP of file \fBlogger\&.cpp\fP\&.
.SS "void Logger::Shutdown ()"

.PP
Definition at line \fB36\fP of file \fBlogger\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Framework from the source code\&.
