.TH "material" 3 "Sun Apr 9 2023" "OpenGL Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
material
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <material\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "glm::vec3 \fBKa\fP"
.br
.ti -1c
.RI "glm::vec3 \fBKd\fP"
.br
.ti -1c
.RI "glm::vec3 \fBKsp\fP"
.br
.ti -1c
.RI "float \fBKsh\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBMaterial\fP &m)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBmaterial\&.h\fP\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "std::ostream & operator<< (std::ostream & os, const \fBMaterial\fP & m)\fC [friend]\fP"

.PP
Definition at line \fB15\fP of file \fBmaterial\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "glm::vec3 material::Ka"

.PP
Definition at line \fB10\fP of file \fBmaterial\&.h\fP\&.
.SS "glm::vec3 material::Kd"

.PP
Definition at line \fB11\fP of file \fBmaterial\&.h\fP\&.
.SS "float material::Ksh"

.PP
Definition at line \fB13\fP of file \fBmaterial\&.h\fP\&.
.SS "glm::vec3 material::Ksp"

.PP
Definition at line \fB12\fP of file \fBmaterial\&.h\fP\&.
.SS "const char* material::name"

.PP
Definition at line \fB8\fP of file \fBmaterial\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Framework from the source code\&.
