.TH "Mesh" 3 "Sun Apr 9 2023" "OpenGL Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mesh
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mesh\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMesh\fP (std::string mesh_id, unsigned int VAO, std::vector< \fBVertex\fP > &vertices, std::vector< unsigned int > &indices, \fBMaterial\fP *\fBmaterial\fP=nullptr, bool has_error=false)"
.br
.ti -1c
.RI "const char * \fBGetMeshId\fP () const"
.br
.ti -1c
.RI "const unsigned int \fBGetVAO\fP () const"
.br
.ti -1c
.RI "const std::vector< \fBVertex\fP > \fBGetVertices\fP () const"
.br
.ti -1c
.RI "const std::vector< unsigned int > \fBGetIndices\fP () const"
.br
.ti -1c
.RI "const \fBMaterial\fP * \fBGetMaterial\fP () const"
.br
.ti -1c
.RI "const bool \fBGetError\fP () const"
.br
.ti -1c
.RI "void \fBHasError\fP (bool error)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBmesh\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Mesh::Mesh (std::string mesh_id, unsigned int VAO, std::vector< \fBVertex\fP > & vertices, std::vector< unsigned int > & indices, \fBMaterial\fP * material = \fCnullptr\fP, bool has_error = \fCfalse\fP)"

.PP
Definition at line \fB3\fP of file \fBmesh\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "const bool Mesh::GetError () const"

.PP
Definition at line \fB37\fP of file \fBmesh\&.cpp\fP\&.
.SS "const std::vector< unsigned int > Mesh::GetIndices () const"

.PP
Definition at line \fB27\fP of file \fBmesh\&.cpp\fP\&.
.SS "const \fBMaterial\fP * Mesh::GetMaterial () const"

.PP
Definition at line \fB32\fP of file \fBmesh\&.cpp\fP\&.
.SS "const char * Mesh::GetMeshId () const"

.PP
Definition at line \fB12\fP of file \fBmesh\&.cpp\fP\&.
.SS "const unsigned int Mesh::GetVAO () const"

.PP
Definition at line \fB17\fP of file \fBmesh\&.cpp\fP\&.
.SS "const std::vector< \fBVertex\fP > Mesh::GetVertices () const"

.PP
Definition at line \fB22\fP of file \fBmesh\&.cpp\fP\&.
.SS "void Mesh::HasError (bool error)"

.PP
Definition at line \fB42\fP of file \fBmesh\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Framework from the source code\&.
