.TH "SceneInput" 3 "Sun Apr 9 2023" "OpenGL Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SceneInput
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <scene_input\&.h>\fP
.PP
Inherits \fBInputController\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSceneInput\fP (\fBScene\fP *scene)"
.br
.ti -1c
.RI "void \fBOnKeyPress\fP (int key, int mods)"
.br
.RI "Method for handling key presses\&. "
.in -1c

Public Member Functions inherited from \fBInputController\fP
.in +1c
.ti -1c
.RI "\fBInputController\fP ()"
.br
.RI "Method for connecting the input controller to a component\&. "
.ti -1c
.RI "\fB~InputController\fP ()"
.br
.ti -1c
.RI "void \fBToogleEvents\fP ()"
.br
.RI "Method for toggling the state of the input controller (active or not) "
.ti -1c
.RI "bool \fBIsActive\fP ()"
.br
.RI "Method for checking the state of the input controller\&. "
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBScene\fP"
.br
.in -1c
.SS "Additional Inherited Members"

.in +1c
.ti -1c
.RI "virtual void \fBOnInputUpdate\fP (double delta_time, int mods)=0"
.br
.RI "Method for handling continous events (like key presses) "
.ti -1c
.RI "virtual void \fBOnKeyPress\fP (int key, int mods)=0"
.br
.RI "Method for handling key presses\&. "
.ti -1c
.RI "virtual void \fBOnKeyRelease\fP (int key, int mods)=0"
.br
.RI "Method for handling key releases\&. "
.ti -1c
.RI "virtual void \fBOnMouseMove\fP (double x_pos, double y_pos, double delta_x, double delta_y)=0"
.br
.RI "Method for handling mouse movement\&. "
.ti -1c
.RI "virtual void \fBOnMouseButtonPress\fP (double x_pos, double y_pos, int button, int mods)=0"
.br
.RI "Method for handling mouse button presses\&. "
.ti -1c
.RI "virtual void \fBOnMouseButttonRelease\fP (double x_pos, double y_pos, int button, int mods)=0"
.br
.RI "Method for handling mouse button releases\&. "
.ti -1c
.RI "virtual void \fBOnMouseScroll\fP (double x_offset, double y_offset)=0"
.br
.RI "Method for handling mouse scroll\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBscene_input\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SceneInput::SceneInput (\fBScene\fP * scene)"

.PP
Definition at line \fB3\fP of file \fBscene_input\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void SceneInput::OnKeyPress (int key, int mods)\fC [virtual]\fP"

.PP
Method for handling key presses\&. 
.PP
\fBParameters\fP
.RS 4
\fIkey\fP The code of the pressed key 
.br
\fImods\fP The code of combination presses with special keys (L_SHIFT, L_ALT, L_CTRL, R_SHIFT, R_ALT, R_CTRL) 
.RE
.PP

.PP
Implements \fBInputController\fP\&.
.PP
Definition at line \fB9\fP of file \fBscene_input\&.cpp\fP\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBScene\fP\fC [friend]\fP"

.PP
Definition at line \fB8\fP of file \fBscene_input\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Framework from the source code\&.
