.TH "src/managers/texture/texture_2D.cpp" 3 "Sun Apr 9 2023" "OpenGL Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/managers/texture/texture_2D.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'texture_2D\&.h'\fP
.br
\fC#include <stb_image\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSTB_IMAGE_IMPLEMENTATION\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define STB_IMAGE_IMPLEMENTATION"

.PP
Definition at line \fB3\fP of file \fBtexture_2D\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Framework from the source code\&.
