.TH "TextureManger" 3 "Sun Apr 9 2023" "OpenGL Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TextureManger
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <texture_manager\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBLoadTexture2D\fP (const char *file_path, const char *name)"
.br
.RI "Method for loading a 2D texture from a file\&. "
.ti -1c
.RI "\fBTexture2D\fP * \fBGetTexture2D\fP (const char *name)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBTexture2D\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB11\fP of file \fBtexture_manager\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBTexture2D\fP * TextureManger::GetTexture2D (const char * name)"

.PP
Definition at line \fB13\fP of file \fBtexture_manager\&.cpp\fP\&.
.SS "void TextureManger::LoadTexture2D (const char * file_path, const char * name)"

.PP
Method for loading a 2D texture from a file\&. 
.PP
\fBParameters\fP
.RS 4
\fIfile_path\fP The path to the texture file 
.br
\fIname\fP The name of the texture with which is identified (given by the caller: crate\&.jpg -> crate) 
.RE
.PP

.PP
Definition at line \fB3\fP of file \fBtexture_manager\&.cpp\fP\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBTexture2D\fP\fC [friend]\fP"

.PP
Definition at line \fB13\fP of file \fBtexture_manager\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Framework from the source code\&.
