.TH "src/managers/texture/texture_manager.h" 3 "Sun Apr 9 2023" "OpenGL Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/managers/texture/texture_manager.h
.SH SYNOPSIS
.br
.PP
\fC#include <unordered_map>\fP
.br
\fC#include <core\&.h>\fP
.br
\fC#include <glad/glad\&.h>\fP
.br
\fC#include 'texture_2D\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTextureManger\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Framework from the source code\&.
