.TH "src/utils/vertex.h" 3 "Sun Apr 9 2023" "OpenGL Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/utils/vertex.h
.SH SYNOPSIS
.br
.PP
\fC#include <glm\&.hpp>\fP
.br
\fC#include 'colour\&.h'\fP
.br
\fC#include 'glm_utils\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBvertex\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBvertex\fP \fBVertex\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBvertex\fP \fBVertex\fP"

.PP
Definition at line \fB8\fP of file \fBvertex\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Framework from the source code\&.
