.TH "window_properties" 3 "Sun Apr 9 2023" "OpenGL Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
window_properties
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <window_properties\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBwindow_properties\fP (const char *\fBtitle\fP, unsigned int \fBwidth\fP, unsigned int \fBheight\fP, double \fBaspect_ration\fP=0\&.0f, bool \fBvsync\fP=GLFW_FALSE, bool resizable=GLFW_FALSE, bool \fBvisible\fP=GLFW_TRUE, bool \fBdecorated\fP=GLFW_TRUE, bool \fBfocused\fP=GLFW_TRUE, bool \fBauto_iconify\fP=GLFW_TRUE, bool \fBfloating\fP=GLFW_TRUE, bool \fBmaximized\fP=GLFW_FALSE, bool \fBcenter_cursor\fP=GLFW_TRUE, int \fBrefresh_rate\fP=60)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBtitle\fP"
.br
.ti -1c
.RI "unsigned int \fBwidth\fP"
.br
.ti -1c
.RI "unsigned int \fBheight\fP"
.br
.ti -1c
.RI "double \fBaspect_ration\fP"
.br
.ti -1c
.RI "bool \fBvsync\fP"
.br
.ti -1c
.RI "bool \fBresiable\fP"
.br
.ti -1c
.RI "bool \fBvisible\fP"
.br
.ti -1c
.RI "bool \fBdecorated\fP"
.br
.ti -1c
.RI "bool \fBfocused\fP"
.br
.ti -1c
.RI "bool \fBauto_iconify\fP"
.br
.ti -1c
.RI "bool \fBfloating\fP"
.br
.ti -1c
.RI "bool \fBmaximized\fP"
.br
.ti -1c
.RI "bool \fBcenter_cursor\fP"
.br
.ti -1c
.RI "int \fBrefresh_rate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBwindow_properties\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "window_properties::window_properties (const char * title, unsigned int width, unsigned int height, double aspect_ration = \fC0\&.0f\fP, bool vsync = \fCGLFW_FALSE\fP, bool resizable = \fCGLFW_FALSE\fP, bool visible = \fCGLFW_TRUE\fP, bool decorated = \fCGLFW_TRUE\fP, bool focused = \fCGLFW_TRUE\fP, bool auto_iconify = \fCGLFW_TRUE\fP, bool floating = \fCGLFW_TRUE\fP, bool maximized = \fCGLFW_FALSE\fP, bool center_cursor = \fCGLFW_TRUE\fP, int refresh_rate = \fC60\fP)\fC [inline]\fP"

.PP
Definition at line \fB27\fP of file \fBwindow_properties\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "double window_properties::aspect_ration"

.PP
Definition at line \fB13\fP of file \fBwindow_properties\&.h\fP\&.
.SS "bool window_properties::auto_iconify"

.PP
Definition at line \fB20\fP of file \fBwindow_properties\&.h\fP\&.
.SS "bool window_properties::center_cursor"

.PP
Definition at line \fB23\fP of file \fBwindow_properties\&.h\fP\&.
.SS "bool window_properties::decorated"

.PP
Definition at line \fB18\fP of file \fBwindow_properties\&.h\fP\&.
.SS "bool window_properties::floating"

.PP
Definition at line \fB21\fP of file \fBwindow_properties\&.h\fP\&.
.SS "bool window_properties::focused"

.PP
Definition at line \fB19\fP of file \fBwindow_properties\&.h\fP\&.
.SS "unsigned int window_properties::height"

.PP
Definition at line \fB12\fP of file \fBwindow_properties\&.h\fP\&.
.SS "bool window_properties::maximized"

.PP
Definition at line \fB22\fP of file \fBwindow_properties\&.h\fP\&.
.SS "int window_properties::refresh_rate"

.PP
Definition at line \fB25\fP of file \fBwindow_properties\&.h\fP\&.
.SS "bool window_properties::resiable"

.PP
Definition at line \fB16\fP of file \fBwindow_properties\&.h\fP\&.
.SS "const char* window_properties::title"

.PP
Definition at line \fB9\fP of file \fBwindow_properties\&.h\fP\&.
.SS "bool window_properties::visible"

.PP
Definition at line \fB17\fP of file \fBwindow_properties\&.h\fP\&.
.SS "bool window_properties::vsync"

.PP
Definition at line \fB15\fP of file \fBwindow_properties\&.h\fP\&.
.SS "unsigned int window_properties::width"

.PP
Definition at line \fB11\fP of file \fBwindow_properties\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Framework from the source code\&.
