.TH "WindowCallbacks" 3 "Sun Apr 9 2023" "OpenGL Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WindowCallbacks
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <window_callbacks\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWindowCallbacks\fP ()=delete"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBWindow\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBwindow_callbacks\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "WindowCallbacks::WindowCallbacks ()\fC [delete]\fP"

.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBWindow\fP\fC [friend]\fP"

.PP
Definition at line \fB10\fP of file \fBwindow_callbacks\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Framework from the source code\&.
