.TH "World" 3 "Sun Apr 9 2023" "OpenGL Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
World
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <world\&.h>\fP
.PP
Inherits \fBInputController\fP\&.
.PP
Inherited by \fBScene\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWorld\fP ()"
.br
.ti -1c
.RI "virtual void \fBInit\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBStartFrame\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBUpdate\fP (double delta_time)=0"
.br
.ti -1c
.RI "virtual void \fBEndFrame\fP ()=0"
.br
.ti -1c
.RI "void \fBRun\fP ()"
.br
.RI "Calls the loop update method while the window is active\&. "
.ti -1c
.RI "void \fBExit\fP ()"
.br
.ti -1c
.RI "double \fBGetDeltaTime\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBInputController\fP
.in +1c
.ti -1c
.RI "\fBInputController\fP ()"
.br
.RI "Method for connecting the input controller to a component\&. "
.ti -1c
.RI "\fB~InputController\fP ()"
.br
.ti -1c
.RI "void \fBToogleEvents\fP ()"
.br
.RI "Method for toggling the state of the input controller (active or not) "
.ti -1c
.RI "bool \fBIsActive\fP ()"
.br
.RI "Method for checking the state of the input controller\&. "
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBInputController\fP
.in +1c
.ti -1c
.RI "virtual void \fBOnInputUpdate\fP (double delta_time, int mods)=0"
.br
.RI "Method for handling continous events (like key presses) "
.ti -1c
.RI "virtual void \fBOnKeyPress\fP (int key, int mods)=0"
.br
.RI "Method for handling key presses\&. "
.ti -1c
.RI "virtual void \fBOnKeyRelease\fP (int key, int mods)=0"
.br
.RI "Method for handling key releases\&. "
.ti -1c
.RI "virtual void \fBOnMouseMove\fP (double x_pos, double y_pos, double delta_x, double delta_y)=0"
.br
.RI "Method for handling mouse movement\&. "
.ti -1c
.RI "virtual void \fBOnMouseButtonPress\fP (double x_pos, double y_pos, int button, int mods)=0"
.br
.RI "Method for handling mouse button presses\&. "
.ti -1c
.RI "virtual void \fBOnMouseButttonRelease\fP (double x_pos, double y_pos, int button, int mods)=0"
.br
.RI "Method for handling mouse button releases\&. "
.ti -1c
.RI "virtual void \fBOnMouseScroll\fP (double x_offset, double y_offset)=0"
.br
.RI "Method for handling mouse scroll\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBworld\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "World::World ()"

.PP
Definition at line \fB3\fP of file \fBworld\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void World::EndFrame ()\fC [pure virtual]\fP"

.SS "void World::Exit ()"

.PP
Definition at line \fB20\fP of file \fBworld\&.cpp\fP\&.
.SS "double World::GetDeltaTime ()"

.PP
Definition at line \fB25\fP of file \fBworld\&.cpp\fP\&.
.SS "virtual void World::Init ()\fC [pure virtual]\fP"

.SS "void World::Run ()"

.PP
Calls the loop update method while the window is active\&. 
.PP
Definition at line \fB9\fP of file \fBworld\&.cpp\fP\&.
.SS "virtual void World::StartFrame ()\fC [pure virtual]\fP"

.SS "virtual void World::Update (double delta_time)\fC [pure virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Framework from the source code\&.
