.TH "src/components/camera/camera_input.h" 3 "Sun Apr 9 2023" "OpenGL Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/components/camera/camera_input.h
.SH SYNOPSIS
.br
.PP
\fC#include 'camera\&.h'\fP
.br
\fC#include '\&.\&./\&.\&./engine/core/input_controller/input_controller\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCameraInput\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Framework from the source code\&.
