.TH "src/utils/colour.h" 3 "Sun Apr 9 2023" "OpenGL Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/utils/colour.h
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBcolour\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBcolour\fP \fBColour\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBColour\fP \fBRED\fP = \fBColour\fP{ 255, 0, 0 }"
.br
.ti -1c
.RI "const \fBColour\fP \fBGREEN\fP = \fBColour\fP{ 0, 255, 0 }"
.br
.ti -1c
.RI "const \fBColour\fP \fBBLUE\fP = \fBColour\fP{ 0, 0, 255 }"
.br
.ti -1c
.RI "const \fBColour\fP \fBWHITE\fP = \fBColour\fP{ 255, 255, 255 }"
.br
.ti -1c
.RI "const \fBColour\fP \fBBLACK\fP = \fBColour\fP{ 0, 0, 0 }"
.br
.ti -1c
.RI "const \fBColour\fP \fBGREY\fP = \fBColour\fP{ 128, 128, 128 }"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBcolour\fP \fBColour\fP"

.PP
Definition at line \fB5\fP of file \fBcolour\&.h\fP\&.
.SH "Variable Documentation"
.PP 
.SS "const \fBColour\fP BLACK = \fBColour\fP{ 0, 0, 0 }"

.PP
Definition at line \fB24\fP of file \fBcolour\&.h\fP\&.
.SS "const \fBColour\fP BLUE = \fBColour\fP{ 0, 0, 255 }"

.PP
Definition at line \fB22\fP of file \fBcolour\&.h\fP\&.
.SS "const \fBColour\fP GREEN = \fBColour\fP{ 0, 255, 0 }"

.PP
Definition at line \fB21\fP of file \fBcolour\&.h\fP\&.
.SS "const \fBColour\fP GREY = \fBColour\fP{ 128, 128, 128 }"

.PP
Definition at line \fB25\fP of file \fBcolour\&.h\fP\&.
.SS "const \fBColour\fP RED = \fBColour\fP{ 255, 0, 0 }"

.PP
Definition at line \fB20\fP of file \fBcolour\&.h\fP\&.
.SS "const \fBColour\fP WHITE = \fBColour\fP{ 255, 255, 255 }"

.PP
Definition at line \fB23\fP of file \fBcolour\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Framework from the source code\&.
