.TH "src/engine/core Directory Reference" 3 "Sun Apr 9 2023" "OpenGL Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/engine/core Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBinput_controller\fP"
.br
.ti -1c
.RI "directory \fBwindow\fP"
.br
.in -1c
