.TH "src/managers/texture Directory Reference" 3 "Sun Apr 9 2023" "OpenGL Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/managers/texture Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBtexture_2D\&.cpp\fP"
.br
.ti -1c
.RI "file \fBtexture_2D\&.h\fP"
.br
.ti -1c
.RI "file \fBtexture_manager\&.cpp\fP"
.br
.ti -1c
.RI "file \fBtexture_manager\&.h\fP"
.br
.in -1c
