.TH "src/engine/engine.h" 3 "Sun Apr 9 2023" "OpenGL Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/engine/engine.h
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./managers/logger/logger\&.h'\fP
.br
\fC#include 'core/window/window\&.h'\fP
.br
\fC#include 'core/window/window_properties\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEngine\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Framework from the source code\&.
