.TH "src/utils/glm_utils.h" 3 "Sun Apr 9 2023" "OpenGL Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/utils/glm_utils.h
.SH SYNOPSIS
.br
.PP
\fC#include <ostream>\fP
.br
\fC#include <glm\&.hpp>\fP
.br
\fC#include <gtc/type_ptr\&.hpp>\fP
.br
\fC#include <gtc/matrix_transform\&.hpp>\fP
.br
\fC#include <gtc/quaternion\&.hpp>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &out, const glm::ivec2 &vec)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &out, const glm::vec2 &vec)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &out, const glm::ivec3 &vec)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &out, const glm::vec3 &vec)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &out, const glm::ivec4 &vec)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &out, const glm::vec4 &vec)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &out, const glm::quat &rot)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::ostream & operator<< (std::ostream & out, const glm::ivec2 & vec)\fC [inline]\fP"

.PP
Definition at line \fB9\fP of file \fBglm_utils\&.h\fP\&.
.SS "std::ostream & operator<< (std::ostream & out, const glm::ivec3 & vec)\fC [inline]\fP"

.PP
Definition at line \fB19\fP of file \fBglm_utils\&.h\fP\&.
.SS "std::ostream & operator<< (std::ostream & out, const glm::ivec4 & vec)\fC [inline]\fP"

.PP
Definition at line \fB29\fP of file \fBglm_utils\&.h\fP\&.
.SS "std::ostream & operator<< (std::ostream & out, const glm::quat & rot)\fC [inline]\fP"

.PP
Definition at line \fB39\fP of file \fBglm_utils\&.h\fP\&.
.SS "std::ostream & operator<< (std::ostream & out, const glm::vec2 & vec)\fC [inline]\fP"

.PP
Definition at line \fB14\fP of file \fBglm_utils\&.h\fP\&.
.SS "std::ostream & operator<< (std::ostream & out, const glm::vec3 & vec)\fC [inline]\fP"

.PP
Definition at line \fB24\fP of file \fBglm_utils\&.h\fP\&.
.SS "std::ostream & operator<< (std::ostream & out, const glm::vec4 & vec)\fC [inline]\fP"

.PP
Definition at line \fB34\fP of file \fBglm_utils\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Framework from the source code\&.
