.TH "src/engine/core/input_controller/input_controller.h" 3 "Sun Apr 9 2023" "OpenGL Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/engine/core/input_controller/input_controller.h
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./window/window\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBInputController\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Framework from the source code\&.
