.TH "src/managers/logger/logger.h" 3 "Sun Apr 9 2023" "OpenGL Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/managers/logger/logger.h
.SH SYNOPSIS
.br
.PP
\fC#include <spdlog/spdlog\&.h>\fP
.br
\fC#include <spdlog/sinks/stdout_color_sinks\&.h>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'log\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLogger\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Framework from the source code\&.
