.TH "src/components/scene/scene.h" 3 "Sun Apr 9 2023" "OpenGL Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/components/scene/scene.h
.SH SYNOPSIS
.br
.PP
\fC#include <unordered_map>\fP
.br
\fC#include '\&.\&./\&.\&./world\&.h'\fP
.br
\fC#include 'scene_input\&.h'\fP
.br
\fC#include '\&.\&./camera/camera\&.h'\fP
.br
\fC#include '\&.\&./camera/camera_input\&.h'\fP
.br
\fC#include '\&.\&./mesh/mesh\&.h'\fP
.br
\fC#include '\&.\&./\&.\&./managers/texture/texture_manager\&.h'\fP
.br
\fC#include '\&.\&./\&.\&./managers/shape/shape_manager\&.h'\fP
.br
\fC#include '\&.\&./\&.\&./managers/shader/shader\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBScene\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Framework from the source code\&.
