.TH "src/components/scene/scene_input.h" 3 "Sun Apr 9 2023" "OpenGL Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/components/scene/scene_input.h
.SH SYNOPSIS
.br
.PP
\fC#include 'scene\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSceneInput\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Framework from the source code\&.
