.TH "src/managers/shader/shader.h" 3 "Sun Apr 9 2023" "OpenGL Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/managers/shader/shader.h
.SH SYNOPSIS
.br
.PP
\fC#include <core\&.h>\fP
.br
\fC#include <glad/glad\&.h>\fP
.br
\fC#include <glfw3\&.h>\fP
.br
\fC#include <glm\&.hpp>\fP
.br
\fC#include <gtc/type_ptr\&.hpp>\fP
.br
\fC#include <string>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBShader\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Framework from the source code\&.
