.TH "src/managers/shape/shape_manager.cpp" 3 "Sun Apr 9 2023" "OpenGL Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/managers/shape/shape_manager.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'shape_manager\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Framework from the source code\&.
