.TH "ShapeManager" 3 "Sun Apr 9 2023" "OpenGL Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ShapeManager
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <shape_manager\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBShapeManager\fP (\fBScene\fP *scene)"
.br
.ti -1c
.RI "void \fBCreateRectangleX\fP (const char *name, float width, float height)"
.br
.ti -1c
.RI "void \fBCreateRectangleY\fP (const char *name, float width, float height)"
.br
.ti -1c
.RI "void \fBCreateRectangleZ\fP (const char *name, float width, float height)"
.br
.ti -1c
.RI "void \fBCreateTriangleX\fP (const char *name, float sideA, float sideB, float sideC, glm::vec3 startPosition)"
.br
.ti -1c
.RI "void \fBCreateTriangleY\fP (const char *name, float sideA, float sideB, float sideC, glm::vec3 startPosition)"
.br
.ti -1c
.RI "void \fBCreateTriangleZ\fP (const char *name, float sideA, float sideB, float sideC, glm::vec3 startPosition)"
.br
.ti -1c
.RI "void \fBCreateCube\fP (const char *name, float width, float height, float length)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBScene\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBshape_manager\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ShapeManager::ShapeManager (\fBScene\fP * scene)"

.PP
Definition at line \fB3\fP of file \fBshape_manager\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void ShapeManager::CreateCube (const char * name, float width, float height, float length)"

.PP
Definition at line \fB81\fP of file \fBshape_manager\&.cpp\fP\&.
.SS "void ShapeManager::CreateRectangleX (const char * name, float width, float height)"

.PP
Definition at line \fB14\fP of file \fBshape_manager\&.cpp\fP\&.
.SS "void ShapeManager::CreateRectangleY (const char * name, float width, float height)"

.PP
Definition at line \fB31\fP of file \fBshape_manager\&.cpp\fP\&.
.SS "void ShapeManager::CreateRectangleZ (const char * name, float width, float height)"

.PP
Definition at line \fB48\fP of file \fBshape_manager\&.cpp\fP\&.
.SS "void ShapeManager::CreateTriangleX (const char * name, float sideA, float sideB, float sideC, glm::vec3 startPosition = \fCglm::vec3(0)\fP)"

.PP
Definition at line \fB65\fP of file \fBshape_manager\&.cpp\fP\&.
.SS "void ShapeManager::CreateTriangleY (const char * name, float sideA, float sideB, float sideC, glm::vec3 startPosition)"

.PP
Definition at line \fB73\fP of file \fBshape_manager\&.cpp\fP\&.
.SS "void ShapeManager::CreateTriangleZ (const char * name, float sideA, float sideB, float sideC, glm::vec3 startPosition)"

.PP
Definition at line \fB77\fP of file \fBshape_manager\&.cpp\fP\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBScene\fP\fC [friend]\fP"

.PP
Definition at line \fB10\fP of file \fBshape_manager\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Framework from the source code\&.
