.TH "Texture2D" 3 "Sun Apr 9 2023" "OpenGL Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Texture2D
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <texture_2D\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTexture2D\fP ()"
.br
.ti -1c
.RI "unsigned int \fBGetTextureID\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBTextureManger\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBtexture_2D\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Texture2D::Texture2D ()"

.PP
Definition at line \fB6\fP of file \fBtexture_2D\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "unsigned int Texture2D::GetTextureID ()"

.PP
Definition at line \fB61\fP of file \fBtexture_2D\&.cpp\fP\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBTextureManger\fP\fC [friend]\fP"

.PP
Definition at line \fB7\fP of file \fBtexture_2D\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Framework from the source code\&.
