.TH "src/managers/texture/texture_2D.h" 3 "Sun Apr 9 2023" "OpenGL Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/managers/texture/texture_2D.h
.SH SYNOPSIS
.br
.PP
\fC#include 'texture_manager\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTexture2D\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Framework from the source code\&.
