.TH "src/engine/core/window/window.h" 3 "Sun Apr 9 2023" "OpenGL Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/engine/core/window/window.h
.SH SYNOPSIS
.br
.PP
\fC#include <memory>\fP
.br
\fC#include <list>\fP
.br
\fC#include 'core\&.h'\fP
.br
\fC#include 'glad/glad\&.h'\fP
.br
\fC#include 'glfw3\&.h'\fP
.br
\fC#include 'glm\&.hpp'\fP
.br
\fC#include 'window_properties\&.h'\fP
.br
\fC#include 'window_callbacks\&.h'\fP
.br
\fC#include '\&.\&./input_controller/input_controller\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWindow\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Framework from the source code\&.
