.TH "src/engine/core/window/window_callbacks.h" 3 "Sun Apr 9 2023" "OpenGL Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/engine/core/window/window_callbacks.h
.SH SYNOPSIS
.br
.PP
\fC#include 'window\&.h'\fP
.br
\fC#include 'glad/glad\&.h'\fP
.br
\fC#include 'glfw3\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWindowCallbacks\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Framework from the source code\&.
