.TH "src/engine/core/window/window_properties.h" 3 "Sun Apr 9 2023" "OpenGL Framework" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/engine/core/window/window_properties.h
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBwindow_properties\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBwindow_properties\fP \fBwindow_properties\fP"
.br
.RI "Structure for keeping window properties\&. "
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBwindow_properties\fP \fBwindow_properties\fP"

.PP
Structure for keeping window properties\&. See https://www.glfw.org/docs/latest/window_guide.html#window_hints for more information 
.PP
Definition at line \fB7\fP of file \fBwindow_properties\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OpenGL Framework from the source code\&.
